apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qqxvu8usp-go 
  janus-idp.io/tekton: qqxvu8usp-go
  backstage.io/kubernetes-id: qqxvu8usp-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qqxvu8usp-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  